# Namespace for MERN Auth App
apiVersion: v1
kind: Namespace
metadata:
  name: mern-auth
  labels:
    app: mern-auth-app
---
# ConfigMap for application configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: mern-auth
data:
  NODE_ENV: "production"
  PORT: "5000"
  CORS_ORIGIN: "http://localhost:8080"
  REACT_APP_API_URL: ""    # Use empty so axios.post(`${process.env.REACT_APP_API_URL}/api…`) → `/api…`
